#PBS -l select=1:ncpus=28:model=bro
#PBS -l site=static_broadwell
#PBS -q normal
#PBS -l walltime=6:00:00
#PBS -N Hydrolight_batch

# set directory
cd /nobackup/jakravit/data/HE60/run/

# load the module and environment
module -a use /swbuild/analytix/tools/modulefiles
module load miniconda3/v4
source activate tf2_8

# run python script
/swbuild/analytix/tools/miniconda3_220407/envs/tf2_8/bin/python run_HE_batch.py case1V6_runlist.txt
